analyzer:
  errors:
    always_use_package_imports: ignore
    annotate_overrides: ignore
    prefer_const_constructors: ignore
    unused_element: ignore
    unused_field: ignore
    unused_local_variable: ignore
  language:
    strict-raw-types: true  # Enforces using generic types
  exclude:
    - '**/*.freezed.dart'  # Exclude Freezed generated files
    - '**/*.g.dart'       # Exclude generated files (common pattern)
    - 'lib/generated/'    # Exclude a specific generated directory
    - 'lib/l10n/'    # Exclude a specific generated directory
    - 'lib/di/'    # Exclude a specific generated directory
    - 'lib/stacked/'    # Exclude a specific generated directory
linter:
  rules:
    - avoid_print  # Discourages usage of `print` statements
    - prefer_single_quotes  # Promotes consistent use of single quotes
    - sort_constructors_first  # Organizes constructors for readability
    - unnecessary_null_checks  # Flags unnecessary null checks
    - unnecessary_overrides  # Identifies unnecessary overrides
    - prefer_const_constructors
    - always_use_package_imports
#    - annotate_overrides