name: d_sdk
description: Datarun Flutter's Reactive SDK
version: 1.0.1
homepage:
publish_to: 'none'
repository: https://github.com/Hamza-ye/drun-sdk-reactive

environment:
  sdk: ">=3.0.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  dio: ^5.8.0+1
  intl: ^0.20.2
  get_it: ^8.0.3
  injectable: ^2.5.0
  shared_preferences: ^2.5.3
  fast_immutable_collections: ^11.0.4
  equatable: ^2.0.7
  flutter_secure_storage: ^9.2.4
  path_provider: ^2.1.5
  path: ^1.9.0
  connectivity_plus: ^6.1.3
  multiple_result: ^5.1.0
  expressions: ^0.2.5+2
  dart_jsonwebtoken: ^3.2.0
  drift: ^2.26.0
  drift_flutter: ^0.2.4
  sqlite3_flutter_libs: ^0.5.32

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.13
  drift_dev: ^2.26.0
  injectable_generator: ^2.7.0
  lints: ^5.1.1
