name: datarun
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.2+2

# analyzer:
# strong-mode: true
# language:
# enableSuperMixins: true

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_localizations:
    sdk: flutter
  material_design_icons_flutter: ^5.0.6996
  d2_remote:
    path: ./data-run-sdk
  equatable: ^2.0.5
  intl: ^0.19.0
  shared_preferences: ^2.0.15
  dio: ^5.0.0
  reflectable: ^4.0.5
  freezed: ^2.5.2
  freezed_annotation: ^2.4.1
  flutter_form_builder: ^9.3.0
  form_builder_validators: ^10.0.1
  rounded_loading_button_plus: ^3.0.1
  percent_indicator: ^4.2.3
  scrollable_positioned_list: ^0.3.8
#  expressions: ^0.2.5+1
  web: ^1.0.0

  ## Temp
#  animated_tree_view: ^2.2.1
  flutter_fancy_tree_view: ^1.6.0
  flutter_tree: ^2.0.3
  reactive_forms: ^17.0.1
  reactive_forms_annotations:
  reactive_dropdown_search: ^4.0.0
  reactive_date_time_picker: ^4.0.0
  scrollable: ^1.0.5
  uuid: ^4.5.0
  device_info_plus: ^10.1.2
  toggle_switch: ^2.3.0
  petitparser: ^4.0.0
  flutter_riverpod: 3.0.0-dev.3
  hooks_riverpod: 3.0.0-dev.3
  riverpod_annotation: 3.0.0-dev.3
  fast_immutable_collections: ^10.2.4
  provider: ^6.1.2
  expression_language: ^1.0.1
  flutter_launcher_icons: ^0.9.3
  expressions: ^0.2.3
  flutter_sticky_header: ^0.7.0
  sliver_tools: ^0.2.12
  collection: ^1.18.0
  connectivity_plus: ^2.1.0
  json_path: ^0.3.1
  logger: ^2.4.0
  flutter_treeview: ^1.0.7+1
  easy_sticky_header: ^1.1.1
  flutter_barcode_scanner: ^2.0.0
  gs1_barcode_parser: ^1.1.0
#  sentry_flutter: ^8.3.0

dev_dependencies:
  test: ^1.21.0
  build_runner: ^2.4.11
#  custom_lint: ^0.6.4
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
  http_mock_adapter: ^0.4.4
  reactive_forms_generator:
  riverpod_generator: 3.0.0-dev.11
  riverpod_lint: 3.0.0-dev.4
  custom_lint: ^0.5.11
  injectable_generator: ^2.6.2
  #  sealed_generators: ^1.13.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - lib/l10n/
    - assets/launcher_icon/
# analyzer:
#   strong-mode: true
#   language:
#     enableSuperMixins: true
flutter_intl:
  enabled: true
