name: d_sdk
description: Datarun Flutter's Reactive SDK
version: 1.0.1
homepage:
publish_to: 'none'
repository: https://github.com/Hamza-ye/drun-sdk-reactive

environment:
  sdk: ">=3.0.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
#  connectivity_plus: ^6.1.4
#  dart_jsonwebtoken: ^3.2.0
  dio: ^5.8.0+1
  drift: ^2.28.0
  drift_flutter: ^0.2.4
  equatable: ^2.0.7
  expressions: ^0.2.5+2
  fast_immutable_collections: ^11.0.4
#  flutter_secure_storage: ^9.2.4
  get_it: ^8.0.3
  injectable: ^2.5.0
  intl: ^0.20.2
  multiple_result: ^5.2.0
  path: ^1.9.1
  path_provider: ^2.1.5
#  shared_preferences: ^2.5.3
  sqlite3_flutter_libs: ^0.5.34
  synchronized: ^3.4.0

dev_dependencies:
  build_runner: ^2.5.4
  drift_dev: ^2.28.0
#  flutter_test:
#    sdk: flutter
  injectable_generator: ^2.7.0
  lints: ^6.0.0
