name: mass_pro
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

# analyzer:
# strong-mode: true
# language:
# enableSuperMixins: true

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_localizations:
    sdk: flutter
  material_design_icons_flutter: ^5.0.6996
  d2_remote:
    path: ./data-run-sdk
  equatable: ^2.0.5
  fast_immutable_collections: ^10.2.4
#  flutter_treeview: ^1.0.7+1
#  table_calendar: ^3.0.9
  intl: ^0.19.0
#  flutter_styled_toast: ^2.1.3
  shared_preferences: ^2.0.15
  rxdart: ^0.27.7
  dartx: ^1.1.0
  dartz: ^0.10.1
  dartlin: ^0.6.3
  dio: ^5.0.0
  reflectable: ^4.0.5
  flutter_riverpod: ^2.5.1
  freezed: ^2.5.2
  freezed_annotation: ^2.4.1
  riverpod_annotation: ^2.3.5
  flutter_form_builder: ^9.3.0
  form_builder_validators: ^10.0.1
  rounded_loading_button_plus: ^3.0.1
  percent_indicator: ^4.2.3
  scrollable_positioned_list: ^0.3.8
  get: ^4.6.6
  expressions: ^0.2.5+1
  web: ^1.0.0

  ## Temp
  animated_tree_view: ^2.2.1
  flutter_fancy_tree_view: ^1.6.0
  arborio: ^0.3.0-beta
  flutter_tree: ^2.0.3
  faker: ^2.1.0
  provider: ^6.1.2
  fast_expressions: ^0.1.7
  reactive_forms: ^17.0.1
  reactive_forms_annotations:
  hooks_riverpod: ^2.5.2
  flutter_hooks: ^0.20.5
  reactive_dropdown_search: ^4.0.0
  reactive_date_time_picker: ^4.0.0
  scrollable: ^1.0.5
  uuid: ^4.5.0
  device_info_plus: ^10.1.2
  toggle_switch: ^2.3.0
  ## End of Temp
#  sentry_flutter: ^8.3.0

dev_dependencies:
  test: ^1.21.0
  flutter_launcher_icons: ^0.13.1
#  auto_route_generator: ^8.0.0
  build_runner: ^2.4.11
#  custom_lint: ^0.6.4
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
  http_mock_adapter: ^0.4.4
  riverpod_generator: ^2.4.0
  riverpod_lint: ^2.3.10
  reactive_forms_generator:
  custom_lint: ^0.6.4
  #  sealed_generators: ^1.13.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - lib/l10n/
    - assets/launcher_icon/
# analyzer:
#   strong-mode: true
#   language:
#     enableSuperMixins: true
flutter_intl:
  enabled: true
