name: d_sdk
description: Datarun Flutter's Reactive SDK
version: 1.0.1
homepage:
publish_to: 'none'
repository: https://github.com/Hamza-ye/drun-sdk-reactive

environment:
  sdk: ">=3.0.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  expressions: ^0.2.5+2
  dio: 5.0.0
  equatable: ^2.0.5
  fast_immutable_collections: ^10.2.4
  intl: ^0.19.0
  path_provider: ^2.1.5
  path: ^1.9.0
  collection: ^1.18.0
  multiple_result: ^5.1.0
  drift: ^2.23.1
#  drift_flutter: ^0.2.4
#  sqlcipher_flutter_libs: ^0.6.5
#  sqlite3: '>=1.8.0 <3.0.0'
  get_it: ^8.0.3
  injectable: ^2.5.0
  flutter_secure_storage: ^4.2.1
  shared_preferences: ^2.0.15
  rxdart: ^0.27.7
  connectivity_plus: ^6.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.7
  http_mock_adapter: ^0.4.4
  lints: ^2.0.1
  drift_dev: ^2.23.1
  injectable_generator: ^2.6.2
